color_theme = "nord"

theme/background = "#131318"
theme/main_bg = "#131318"
theme/main_fg = "#e5e1e9"
theme inactive_fg = "#928f9c"
theme/active_fg = "#e5e1e9"
theme/proc_misc = "#c4c0ff"
theme/proc_progress = "#c4c0ff"
theme/proc_gradient = "#c4c0ff"
theme/cpu = "#c6c3e9"
theme/mem = "#feacef"
theme/net_download = "#c4c0ff"
theme/net_upload = "#ffb4ab"
theme/graph_bg = "#474551"

proc_multithreading = true
proc_tree = true
proc_colors = true
proc_gradient = true
proc_reversed = false
proc_filter_kernel = true
proc_aggregate = true
proc_per_core = true

show_disks = true
show_swap = true
show_swap_labels = true
show_gpu = true
show_table = true
show_graph = true

log_level = "warning"
update_time_ms = 1000

vim_keys = true