no-border=yes
keep-open=yes
force-window=immediate
osc=yes
osd-bar-align-y=0.95
osd-font-size=28
osd-color='#e5e1e9'
osd-border-color='#131318'
osd-back-color='#131318EE'

background-color='#131318'

sub-color='#e5e1e9'
sub-border-color='#131318'
sub-back-color='#131318CC'
sub-font-size=16
sub-blur=0.2

screenshot-format=png
screenshot-template='%t-%F-%04n'
screenshot-dir=~~/Pictures/Screenshots

ytdl-format=bestvideo[height<=?1080]+bestaudio/best

hwdec=auto-safe
profile=gpu-hq
gpu-api=opengl
target-colorspace-hint=yes

input-default-bindings=yes
cursor-autohide=1000